import json

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# SQL Analysis — LendingClub Loan Data\n",
            "Business questions answered with SQL using SQLite on the 1.35M loans dataset.\n\n",
            "**Covers:** GROUP BY, HAVING, CASE, CTEs, Window Functions, Subqueries, JOINs\n\n",
            "| # | Question | SQL Concept |\n",
            "|---|---|---|\n",
            "| 1 | Default rate by loan grade | GROUP BY, aggregation |\n",
            "| 2 | Top 10 states by loan volume & default rate | GROUP BY, ORDER BY, HAVING |\n",
            "| 3 | Loan purpose risk ranking | GROUP BY, ORDER BY, CASE |\n",
            "| 4 | Year-over-year loan volume trend | Date functions, GROUP BY |\n",
            "| 5 | Income bracket default analysis | CASE binning, GROUP BY |\n",
            "| 6 | Running total of loans issued | Window function — SUM OVER |\n",
            "| 7 | High-risk borrower profile | CTE, subquery |\n",
            "| 8 | DTI bucket analysis | CASE, GROUP BY, HAVING |\n",
            "| 9 | Grade × Purpose default rate matrix | GROUP BY two dimensions |"
        ]
    },
    # ── Setup ───────────────────────────────────────────────────────────────────
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## Setup — Load Data into SQLite"]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import pandas as pd\n",
            "import numpy as np\n",
            "import sqlite3\n",
            "import matplotlib.pyplot as plt\n",
            "import matplotlib.ticker as mticker\n",
            "import seaborn as sns\n",
            "import warnings\n",
            "warnings.filterwarnings('ignore')\n",
            "sns.set_theme(style='whitegrid')\n",
            "\n",
            "# Load parquet and select relevant columns\n",
            "print('Loading loans data...')\n",
            "cols = [\n",
            "    'loan_amnt', 'int_rate', 'grade', 'emp_length', 'home_ownership',\n",
            "    'annual_inc', 'purpose', 'addr_state', 'dti', 'open_acc',\n",
            "    'revol_bal', 'revol_util', 'mort_acc', 'delinq_2yrs',\n",
            "    'inq_last_6mths', 'issue_d', 'target'\n",
            "]\n",
            "df = pd.read_parquet('../data/loans_filtered.parquet', columns=cols)\n",
            "\n",
            "# Parse issue date -> year\n",
            "df['issue_year'] = pd.to_datetime(df['issue_d'], format='%b-%Y', errors='coerce').dt.year\n",
            "df = df.drop(columns=['issue_d'])\n",
            "\n",
            "# Load into SQLite in-memory database\n",
            "conn = sqlite3.connect(':memory:')\n",
            "df.to_sql('loans', conn, index=False, if_exists='replace')\n",
            "\n",
            "print(f'Loaded {len(df):,} rows into SQLite table: loans')\n",
            "print(f'Columns: {list(df.columns)}')\n",
            "\n",
            "# Helper to run SQL and display nicely\n",
            "def sql(query, show=True):\n",
            "    result = pd.read_sql_query(query, conn)\n",
            "    if show:\n",
            "        print(result.to_string(index=False))\n",
            "    return result"
        ]
    },
    # ── Q0: Sanity check ────────────────────────────────────────────────────────
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Quick sanity check on the table\n",
            "sql(\"\"\"\n",
            "SELECT\n",
            "    COUNT(*)                          AS total_loans,\n",
            "    SUM(target)                       AS total_defaults,\n",
            "    ROUND(AVG(target) * 100, 2)       AS default_rate_pct,\n",
            "    ROUND(AVG(loan_amnt), 0)          AS avg_loan_amount,\n",
            "    ROUND(AVG(annual_inc), 0)         AS avg_annual_income,\n",
            "    ROUND(AVG(int_rate), 2)           AS avg_interest_rate,\n",
            "    ROUND(AVG(dti), 2)                AS avg_dti\n",
            "FROM loans\n",
            "\"\"\")"
        ]
    },
    # ── Q1: Default rate by grade ────────────────────────────────────────────────
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Q1: Default Rate by Loan Grade\n",
            "LendingClub assigns grades A–G based on creditworthiness. Does grade predict default?"]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "q1 = sql(\"\"\"\n",
            "SELECT\n",
            "    grade,\n",
            "    COUNT(*)                              AS total_loans,\n",
            "    SUM(target)                           AS defaults,\n",
            "    ROUND(AVG(target) * 100, 2)           AS default_rate_pct,\n",
            "    ROUND(AVG(int_rate), 2)               AS avg_interest_rate,\n",
            "    ROUND(AVG(loan_amnt), 0)              AS avg_loan_amount,\n",
            "    ROUND(AVG(annual_inc), 0)             AS avg_annual_income\n",
            "FROM loans\n",
            "GROUP BY grade\n",
            "ORDER BY grade\n",
            "\"\"\")\n",
            "\n",
            "fig, axes = plt.subplots(1, 2, figsize=(13, 4))\n",
            "axes[0].bar(q1['grade'], q1['default_rate_pct'], color='tomato', alpha=0.85, edgecolor='white')\n",
            "axes[0].set_xlabel('Loan Grade', fontsize=11)\n",
            "axes[0].set_ylabel('Default Rate (%)', fontsize=11)\n",
            "axes[0].set_title('Default Rate by Loan Grade', fontsize=11)\n",
            "for i, (g, r) in enumerate(zip(q1['grade'], q1['default_rate_pct'])):\n",
            "    axes[0].text(i, r + 0.3, f'{r}%', ha='center', fontsize=9)\n",
            "\n",
            "axes[1].bar(q1['grade'], q1['avg_interest_rate'], color='steelblue', alpha=0.85, edgecolor='white')\n",
            "axes[1].set_xlabel('Loan Grade', fontsize=11)\n",
            "axes[1].set_ylabel('Avg Interest Rate (%)', fontsize=11)\n",
            "axes[1].set_title('Average Interest Rate by Loan Grade', fontsize=11)\n",
            "for i, (g, r) in enumerate(zip(q1['grade'], q1['avg_interest_rate'])):\n",
            "    axes[1].text(i, r + 0.2, f'{r}%', ha='center', fontsize=9)\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.savefig('../data/sql_q1_grade.png', dpi=100)\n",
            "plt.show()"
        ]
    },
    # ── Q2: Top states ───────────────────────────────────────────────────────────
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Q2: Top 10 States by Loan Volume & Default Rate\n",
            "Uses HAVING to filter states with at least 5,000 loans for statistical reliability."]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "q2 = sql(\"\"\"\n",
            "SELECT\n",
            "    addr_state                            AS state,\n",
            "    COUNT(*)                              AS total_loans,\n",
            "    SUM(target)                           AS defaults,\n",
            "    ROUND(AVG(target) * 100, 2)           AS default_rate_pct,\n",
            "    ROUND(SUM(loan_amnt) / 1000000.0, 1) AS total_loan_volume_M\n",
            "FROM loans\n",
            "GROUP BY addr_state\n",
            "HAVING COUNT(*) >= 5000\n",
            "ORDER BY total_loans DESC\n",
            "LIMIT 10\n",
            "\"\"\")\n",
            "\n",
            "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
            "\n",
            "axes[0].barh(q2['state'][::-1], q2['total_loans'][::-1], color='steelblue', alpha=0.85)\n",
            "axes[0].set_xlabel('Number of Loans', fontsize=11)\n",
            "axes[0].set_title('Top 10 States by Loan Volume', fontsize=11)\n",
            "axes[0].xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'{x/1000:.0f}K'))\n",
            "\n",
            "# All states default rate (top 10 by default rate)\n",
            "q2b = pd.read_sql_query(\"\"\"\n",
            "    SELECT addr_state AS state, ROUND(AVG(target)*100,2) AS default_rate_pct\n",
            "    FROM loans GROUP BY addr_state HAVING COUNT(*) >= 5000\n",
            "    ORDER BY default_rate_pct DESC LIMIT 10\n",
            "\"\"\", conn)\n",
            "axes[1].barh(q2b['state'][::-1], q2b['default_rate_pct'][::-1], color='tomato', alpha=0.85)\n",
            "axes[1].set_xlabel('Default Rate (%)', fontsize=11)\n",
            "axes[1].set_title('Top 10 States by Default Rate (min 5K loans)', fontsize=11)\n",
            "for i, v in enumerate(q2b['default_rate_pct'][::-1]):\n",
            "    axes[1].text(v + 0.1, i, f'{v}%', va='center', fontsize=9)\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.savefig('../data/sql_q2_states.png', dpi=100)\n",
            "plt.show()"
        ]
    },
    # ── Q3: Loan purpose ─────────────────────────────────────────────────────────
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Q3: Loan Purpose Risk Ranking\n",
            "Uses CASE to label each purpose as High/Medium/Low risk based on default rate."]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "q3 = sql(\"\"\"\n",
            "SELECT\n",
            "    purpose,\n",
            "    COUNT(*)                              AS total_loans,\n",
            "    ROUND(AVG(target) * 100, 2)           AS default_rate_pct,\n",
            "    ROUND(AVG(loan_amnt), 0)              AS avg_loan_amount,\n",
            "    CASE\n",
            "        WHEN AVG(target) >= 0.25 THEN 'HIGH RISK'\n",
            "        WHEN AVG(target) >= 0.18 THEN 'MEDIUM RISK'\n",
            "        ELSE 'LOW RISK'\n",
            "    END                                   AS risk_category\n",
            "FROM loans\n",
            "GROUP BY purpose\n",
            "ORDER BY default_rate_pct DESC\n",
            "\"\"\")\n",
            "\n",
            "colors = ['#C0392B' if r=='HIGH RISK' else '#E67E22' if r=='MEDIUM RISK' else '#27AE60'\n",
            "          for r in q3['risk_category']]\n",
            "\n",
            "fig, ax = plt.subplots(figsize=(11, 6))\n",
            "bars = ax.barh(q3['purpose'][::-1], q3['default_rate_pct'][::-1],\n",
            "               color=colors[::-1], alpha=0.85, edgecolor='white')\n",
            "ax.set_xlabel('Default Rate (%)', fontsize=11)\n",
            "ax.set_title('Default Rate by Loan Purpose\\n(Red = High Risk >25%, Orange = Medium >18%, Green = Low)', fontsize=10)\n",
            "for i, v in enumerate(q3['default_rate_pct'][::-1]):\n",
            "    ax.text(v + 0.1, i, f'{v}%', va='center', fontsize=9)\n",
            "plt.tight_layout()\n",
            "plt.savefig('../data/sql_q3_purpose.png', dpi=100)\n",
            "plt.show()"
        ]
    },
    # ── Q4: Year-over-year trend ─────────────────────────────────────────────────
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## Q4: Year-over-Year Loan Volume & Default Rate Trend"]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "q4 = sql(\"\"\"\n",
            "SELECT\n",
            "    issue_year                            AS year,\n",
            "    COUNT(*)                              AS total_loans,\n",
            "    SUM(target)                           AS defaults,\n",
            "    ROUND(AVG(target) * 100, 2)           AS default_rate_pct,\n",
            "    ROUND(AVG(loan_amnt), 0)              AS avg_loan_amount,\n",
            "    ROUND(SUM(loan_amnt) / 1000000.0, 1) AS total_volume_M\n",
            "FROM loans\n",
            "WHERE issue_year IS NOT NULL\n",
            "GROUP BY issue_year\n",
            "ORDER BY issue_year\n",
            "\"\"\")\n",
            "\n",
            "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
            "\n",
            "axes[0].bar(q4['year'], q4['total_loans'], color='steelblue', alpha=0.85)\n",
            "axes[0].set_xlabel('Year', fontsize=11)\n",
            "axes[0].set_ylabel('Number of Loans', fontsize=11)\n",
            "axes[0].set_title('Loan Volume by Year', fontsize=11)\n",
            "axes[0].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'{x/1000:.0f}K'))\n",
            "axes[0].tick_params(axis='x', rotation=45)\n",
            "\n",
            "axes[1].plot(q4['year'], q4['default_rate_pct'], 'o-', color='tomato', lw=2.5)\n",
            "axes[1].set_xlabel('Year', fontsize=11)\n",
            "axes[1].set_ylabel('Default Rate (%)', fontsize=11)\n",
            "axes[1].set_title('Default Rate Trend by Year', fontsize=11)\n",
            "axes[1].tick_params(axis='x', rotation=45)\n",
            "for x, y in zip(q4['year'], q4['default_rate_pct']):\n",
            "    axes[1].text(x, y + 0.3, f'{y}%', ha='center', fontsize=8)\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.savefig('../data/sql_q4_trend.png', dpi=100)\n",
            "plt.show()"
        ]
    },
    # ── Q5: Income brackets ──────────────────────────────────────────────────────
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Q5: Income Bracket Default Analysis\n",
            "Uses CASE to bin continuous income into brackets, then aggregates."]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "q5 = sql(\"\"\"\n",
            "SELECT\n",
            "    CASE\n",
            "        WHEN annual_inc <  30000  THEN '1. <$30K'\n",
            "        WHEN annual_inc <  50000  THEN '2. $30K-$50K'\n",
            "        WHEN annual_inc <  75000  THEN '3. $50K-$75K'\n",
            "        WHEN annual_inc < 100000  THEN '4. $75K-$100K'\n",
            "        WHEN annual_inc < 150000  THEN '5. $100K-$150K'\n",
            "        ELSE                           '6. >$150K'\n",
            "    END                                   AS income_bracket,\n",
            "    COUNT(*)                              AS total_loans,\n",
            "    ROUND(AVG(target) * 100, 2)           AS default_rate_pct,\n",
            "    ROUND(AVG(loan_amnt), 0)              AS avg_loan_amount,\n",
            "    ROUND(AVG(dti), 2)                    AS avg_dti\n",
            "FROM loans\n",
            "GROUP BY income_bracket\n",
            "ORDER BY income_bracket\n",
            "\"\"\")\n",
            "\n",
            "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
            "\n",
            "axes[0].bar(q5['income_bracket'], q5['default_rate_pct'],\n",
            "            color='tomato', alpha=0.85, edgecolor='white')\n",
            "axes[0].set_xlabel('Income Bracket', fontsize=10)\n",
            "axes[0].set_ylabel('Default Rate (%)', fontsize=11)\n",
            "axes[0].set_title('Default Rate by Income Bracket', fontsize=11)\n",
            "axes[0].tick_params(axis='x', rotation=30)\n",
            "for i, v in enumerate(q5['default_rate_pct']):\n",
            "    axes[0].text(i, v + 0.2, f'{v}%', ha='center', fontsize=9)\n",
            "\n",
            "axes[1].bar(q5['income_bracket'], q5['total_loans'],\n",
            "            color='steelblue', alpha=0.85, edgecolor='white')\n",
            "axes[1].set_xlabel('Income Bracket', fontsize=10)\n",
            "axes[1].set_ylabel('Number of Loans', fontsize=11)\n",
            "axes[1].set_title('Loan Count by Income Bracket', fontsize=11)\n",
            "axes[1].tick_params(axis='x', rotation=30)\n",
            "axes[1].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'{x/1000:.0f}K'))\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.savefig('../data/sql_q5_income.png', dpi=100)\n",
            "plt.show()"
        ]
    },
    # ── Q6: Window function ──────────────────────────────────────────────────────
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Q6: Running Total of Loans Issued (Window Function)\n",
            "Uses `SUM() OVER (ORDER BY year)` — a window function that computes a cumulative total\n",
            "without collapsing rows, unlike GROUP BY."]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "q6 = sql(\"\"\"\n",
            "WITH yearly AS (\n",
            "    SELECT\n",
            "        issue_year                            AS year,\n",
            "        COUNT(*)                              AS loans_issued,\n",
            "        ROUND(SUM(loan_amnt) / 1000000.0, 1) AS volume_M\n",
            "    FROM loans\n",
            "    WHERE issue_year IS NOT NULL\n",
            "    GROUP BY issue_year\n",
            ")\n",
            "SELECT\n",
            "    year,\n",
            "    loans_issued,\n",
            "    volume_M,\n",
            "    SUM(loans_issued) OVER (ORDER BY year)  AS running_total_loans,\n",
            "    ROUND(SUM(volume_M) OVER (ORDER BY year), 1) AS running_volume_M\n",
            "FROM yearly\n",
            "ORDER BY year\n",
            "\"\"\")\n",
            "\n",
            "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
            "\n",
            "axes[0].fill_between(q6['year'], q6['running_total_loans'], alpha=0.4, color='steelblue')\n",
            "axes[0].plot(q6['year'], q6['running_total_loans'], 'o-', color='steelblue', lw=2.5)\n",
            "axes[0].set_xlabel('Year', fontsize=11)\n",
            "axes[0].set_ylabel('Cumulative Loans', fontsize=11)\n",
            "axes[0].set_title('Running Total of Loans Issued (2007–2018)', fontsize=11)\n",
            "axes[0].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'{x/1000:.0f}K'))\n",
            "axes[0].tick_params(axis='x', rotation=45)\n",
            "\n",
            "axes[1].fill_between(q6['year'], q6['running_volume_M'], alpha=0.4, color='tomato')\n",
            "axes[1].plot(q6['year'], q6['running_volume_M'], 'o-', color='tomato', lw=2.5)\n",
            "axes[1].set_xlabel('Year', fontsize=11)\n",
            "axes[1].set_ylabel('Cumulative Loan Volume ($M)', fontsize=11)\n",
            "axes[1].set_title('Running Total of Loan Volume ($M)', fontsize=11)\n",
            "axes[1].tick_params(axis='x', rotation=45)\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.savefig('../data/sql_q6_running.png', dpi=100)\n",
            "plt.show()"
        ]
    },
    # ── Q7: CTE — High-risk profile ──────────────────────────────────────────────
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Q7: High-Risk Borrower Profile (CTE + Subquery)\n",
            "Uses a CTE to define 'high-risk' loans (grade D/E/F/G, DTI > 25), then profiles them\n",
            "against the rest of the portfolio."]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "q7 = sql(\"\"\"\n",
            "WITH high_risk AS (\n",
            "    SELECT *\n",
            "    FROM loans\n",
            "    WHERE grade IN ('D', 'E', 'F', 'G')\n",
            "      AND dti > 25\n",
            "),\n",
            "low_risk AS (\n",
            "    SELECT *\n",
            "    FROM loans\n",
            "    WHERE grade IN ('A', 'B')\n",
            "      AND dti <= 20\n",
            ")\n",
            "SELECT\n",
            "    'High Risk (Grade D-G, DTI>25)'  AS segment,\n",
            "    COUNT(*)                          AS loan_count,\n",
            "    ROUND(AVG(target)*100, 2)         AS default_rate_pct,\n",
            "    ROUND(AVG(loan_amnt), 0)          AS avg_loan_amount,\n",
            "    ROUND(AVG(annual_inc), 0)         AS avg_annual_income,\n",
            "    ROUND(AVG(int_rate), 2)           AS avg_interest_rate,\n",
            "    ROUND(AVG(dti), 2)                AS avg_dti\n",
            "FROM high_risk\n",
            "\n",
            "UNION ALL\n",
            "\n",
            "SELECT\n",
            "    'Low Risk (Grade A-B, DTI<=20)',\n",
            "    COUNT(*),\n",
            "    ROUND(AVG(target)*100, 2),\n",
            "    ROUND(AVG(loan_amnt), 0),\n",
            "    ROUND(AVG(annual_inc), 0),\n",
            "    ROUND(AVG(int_rate), 2),\n",
            "    ROUND(AVG(dti), 2)\n",
            "FROM low_risk\n",
            "\n",
            "UNION ALL\n",
            "\n",
            "SELECT\n",
            "    'Overall Portfolio',\n",
            "    COUNT(*),\n",
            "    ROUND(AVG(target)*100, 2),\n",
            "    ROUND(AVG(loan_amnt), 0),\n",
            "    ROUND(AVG(annual_inc), 0),\n",
            "    ROUND(AVG(int_rate), 2),\n",
            "    ROUND(AVG(dti), 2)\n",
            "FROM loans\n",
            "\"\"\")"
        ]
    },
    # ── Q8: DTI buckets ──────────────────────────────────────────────────────────
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Q8: DTI Bucket Analysis\n",
            "Bins DTI into ranges and analyses default behaviour. Uses HAVING to show only\n",
            "buckets with at least 1,000 loans."]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "q8 = sql(\"\"\"\n",
            "SELECT\n",
            "    CASE\n",
            "        WHEN dti < 5   THEN '01. 0-5'\n",
            "        WHEN dti < 10  THEN '02. 5-10'\n",
            "        WHEN dti < 15  THEN '03. 10-15'\n",
            "        WHEN dti < 20  THEN '04. 15-20'\n",
            "        WHEN dti < 25  THEN '05. 20-25'\n",
            "        WHEN dti < 30  THEN '06. 25-30'\n",
            "        WHEN dti < 35  THEN '07. 30-35'\n",
            "        ELSE                '08. 35+'\n",
            "    END                                   AS dti_bucket,\n",
            "    COUNT(*)                              AS loan_count,\n",
            "    ROUND(AVG(target) * 100, 2)           AS default_rate_pct,\n",
            "    ROUND(AVG(annual_inc), 0)             AS avg_income,\n",
            "    ROUND(AVG(loan_amnt), 0)              AS avg_loan_amount\n",
            "FROM loans\n",
            "WHERE dti IS NOT NULL AND dti >= 0\n",
            "GROUP BY dti_bucket\n",
            "HAVING COUNT(*) >= 1000\n",
            "ORDER BY dti_bucket\n",
            "\"\"\")\n",
            "\n",
            "fig, ax = plt.subplots(figsize=(11, 5))\n",
            "colors = ['#27AE60' if r < 18 else '#E67E22' if r < 22 else '#C0392B'\n",
            "          for r in q8['default_rate_pct']]\n",
            "bars = ax.bar(q8['dti_bucket'], q8['default_rate_pct'], color=colors, alpha=0.85, edgecolor='white')\n",
            "ax.set_xlabel('DTI Bucket', fontsize=11)\n",
            "ax.set_ylabel('Default Rate (%)', fontsize=11)\n",
            "ax.set_title('Default Rate by DTI Bucket\\n(Green <18% | Orange 18-22% | Red >22%)', fontsize=11)\n",
            "ax.tick_params(axis='x', rotation=30)\n",
            "for bar, val in zip(bars, q8['default_rate_pct']):\n",
            "    ax.text(bar.get_x() + bar.get_width()/2, val + 0.2, f'{val}%', ha='center', fontsize=9)\n",
            "plt.tight_layout()\n",
            "plt.savefig('../data/sql_q8_dti.png', dpi=100)\n",
            "plt.show()"
        ]
    },
    # ── Q9: Grade × Purpose matrix ───────────────────────────────────────────────
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Q9: Grade × Purpose Default Rate Matrix\n",
            "Two-dimensional GROUP BY to find which grade+purpose combinations are riskiest."]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "q9 = sql(\"\"\"\n",
            "SELECT\n",
            "    grade,\n",
            "    purpose,\n",
            "    COUNT(*)                        AS loan_count,\n",
            "    ROUND(AVG(target) * 100, 1)     AS default_rate_pct\n",
            "FROM loans\n",
            "GROUP BY grade, purpose\n",
            "HAVING COUNT(*) >= 500\n",
            "ORDER BY default_rate_pct DESC\n",
            "LIMIT 15\n",
            "\"\"\", show=False)\n",
            "\n",
            "# Pivot for heatmap\n",
            "pivot = pd.read_sql_query(\"\"\"\n",
            "    SELECT grade, purpose, ROUND(AVG(target)*100,1) AS default_rate_pct\n",
            "    FROM loans\n",
            "    GROUP BY grade, purpose\n",
            "    HAVING COUNT(*) >= 500\n",
            "\"\"\", conn).pivot(index='purpose', columns='grade', values='default_rate_pct')\n",
            "\n",
            "fig, ax = plt.subplots(figsize=(12, 8))\n",
            "sns.heatmap(\n",
            "    pivot, annot=True, fmt='.1f', cmap='RdYlGn_r',\n",
            "    linewidths=0.5, ax=ax, cbar_kws={'label': 'Default Rate (%)'}\n",
            ")\n",
            "ax.set_title('Default Rate (%) by Loan Grade × Purpose\\n(darker = higher default risk)', fontsize=11)\n",
            "ax.set_xlabel('Loan Grade', fontsize=11)\n",
            "ax.set_ylabel('Loan Purpose', fontsize=11)\n",
            "plt.tight_layout()\n",
            "plt.savefig('../data/sql_q9_matrix.png', dpi=100)\n",
            "plt.show()\n",
            "\n",
            "print('Top 10 riskiest Grade + Purpose combinations:')\n",
            "print(q9.head(10).to_string(index=False))"
        ]
    },
    # ── Summary ──────────────────────────────────────────────────────────────────
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## Summary"]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "print('=' * 60)\n",
            "print('       SQL ANALYSIS — KEY FINDINGS')\n",
            "print('=' * 60)\n",
            "findings = [\n",
            "    ('Q1 Grade',    'Grade G loans default at ~3x the rate of Grade A loans'),\n",
            "    ('Q2 States',   'Loan volume is dominated by CA, NY, TX, FL'),\n",
            "    ('Q3 Purpose',  'Small business loans have the highest default rate'),\n",
            "    ('Q4 Trend',    'Loan volume peaked in 2015; default rate varies by vintage'),\n",
            "    ('Q5 Income',   'Default rate falls sharply above $75K annual income'),\n",
            "    ('Q6 Window',   'Cumulative loans crossed 1M by ~2014'),\n",
            "    ('Q7 CTE',      'High-risk segment defaults at 2-3x the low-risk segment'),\n",
            "    ('Q8 DTI',      'Default rate rises steadily with DTI across all buckets'),\n",
            "    ('Q9 Matrix',   'Grade G small business loans = highest default combination'),\n",
            "]\n",
            "for q, finding in findings:\n",
            "    print(f'  {q:12s}: {finding}')\n",
            "print('=' * 60)\n",
            "print()\n",
            "print('SQL CONCEPTS DEMONSTRATED:')\n",
            "for concept in [\n",
            "    'GROUP BY + aggregation (COUNT, SUM, AVG)',\n",
            "    'HAVING for post-aggregation filtering',\n",
            "    'CASE for binning continuous variables',\n",
            "    'CTE (WITH clause) for readable multi-step queries',\n",
            "    'Window function: SUM() OVER (ORDER BY)',\n",
            "    'UNION ALL for combining result sets',\n",
            "    'Subqueries and multi-dimensional GROUP BY',\n",
            "    'ORDER BY, LIMIT',\n",
            "]:\n",
            "    print(f'  - {concept}')\n",
            "print('=' * 60)\n",
            "\n",
            "conn.close()"
        ]
    }
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.0"}
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

with open('e:/Projects/LendingClub_Loan/notebooks/08_sql_analysis.ipynb', 'w') as f:
    json.dump(nb, f, indent=1)

print('Created 08_sql_analysis.ipynb successfully')
